# Generated by Django 2.1.7 on 2019-02-17 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField(default='Esta receta no tiene instrucciones.')),
                ('plate', models.CharField(choices=[('Entrante', 'Primero'), ('Principal', 'Segundo'), ('Postre', 'Tercero')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recetas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Profile')),
            ],
        ),
    ]
