# Generated by Django 2.1.7 on 2019-02-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premio',
            name='category',
            field=models.CharField(blank=True, choices=[('colaborador', 'Premio Colaborador'), ('sin_premio', 'Sin premio')], default='sin_premio', max_length=50, null=True),
        ),
    ]
