# Generated by Django 2.1.7 on 2019-02-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20190217_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premio',
            name='category',
            field=models.CharField(choices=[('C', 'Premio Colaborador'), ('SP', 'Sin premio')], default='SP', max_length=50),
        ),
    ]
